use Employee;

SELECT * FROM COMPANIES;

CREATE TABLE COMPANIES(CID INT PRIMARY KEY,CNAME VARCHAR(30) NOT NULL,LOCATION VARCHAR(30) NOT NULL);

INSERT INTO COMPANIES VALUES(5,'ORIGIN','AHAMADHABADH')

--cross join

SELECT EMP.ENAME,DEPT.DNAME,CNAME FROM EMP CROSS JOIN DEPT,COMPANIES;

SELECT E.SALARY,E.COMM,D.LOC FROM EMP E CROSS JOIN DEPT D;

SELECT E.ENAME,E.SALARY*12,D.DNAME,D.LOC FROM EMP E CROSS JOIN DEPT D;


--EQUI JOIN 

SELECT E.ENAME,D.DNAME FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO;

SELECT E.ENAME,E.SALARY/2 AS HALF_TERM_SALARY,D.* FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO;

SELECT E.*,D.LOC FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO AND D.DNAME='OPERATIONS';

SELECT E.ENAME,E.JOB,E.SALARY,D.LOC FROM EMP E,DEPT D WHERE E.DEPTNO=D.DEPTNO AND D.DNAME='ANALYST' AND SALARY BETWEEN 1000 AND 3000;

--INNER JOIN 
SELECT * FROM EMP;

SELECT E.*,D.* FROM EMP E INNER JOIN DEPT D ON E.HIREDATE LIKE '%JAN%' AND E.DEPTNO=D.DEPTNO;

SELECT E.SALARY*12,E.COMM/2,D.DNAME FROM EMP E INNER JOIN DEPT D ON MGR IS NULL AND E.DEPTNO=D.DEPTNO;

SELECT E.ENAME,E.DEPTNO,E.JOB,D.DNAME,D.DEPTNO FROM EMP E INNER JOIN DEPT D ON E.DEPTNO > D.DEPTNO;


--SELF JOIN

SELECT E1.* FROM EMP E1,EMP E2 WHERE E2.SALARY=E1.SALARY AND E2.ENAME='MARTIN';

SELECT E1.ENAME AS EMPLOYEE_NME,E2.ENAME MANAGER_NAME FROM EMP E1,EMP E2 WHERE E1.MGR=E2.EMPNO;

---OUTER JOIN

--LEFT OUTER JOIN

SELECT E.ENAME,D.DNAME FROM EMP E LEFT JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

--RIGHT OUTER JOIN

SELECT D.DNAME,E.ENAME FROM EMP E RIGHT JOIN DEPT D ON E.DEPTNO=D.DEPTNO;

--FULL JOIN 

SELECT E.ENAME,D.DNAME FROM EMP E FULL JOIN DEPT D ON E.DEPTNO=D.DEPTNO;
